steps:
  - name: "gcr.io/cloud-builders/npm"
    dir: "peerprep"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    dir: "peerprep"
    args: ["run", "create-env"]
    env:
      - "REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}"
      - "REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}"
      - "REACT_APP_FIREBASE_DATABASE_URL=${_REACT_APP_FIREBASE_DATABASE_URL}"
      - "REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID}"
      - "REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}"
      - "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}"
      - "REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID}"
      - "REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}"
      - "COMMIT_SHA=${COMMIT_SHA}"
  # build the container image using the docker builder
  - name: "gcr.io/cloud-builders/docker"
    dir: "peerprep"
    args:
      [
        "build",
        "--build-arg",
        "NODE_ENV=production",
        "-t",
        "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA",
        ".",
      ]

  # push the container image to Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    dir: "peerprep"
    args:
      ["push", "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"]

  # Deploy the container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_LOCATION}
      - --set-env-vars=REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY},REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN},REACT_APP_FIREBASE_DATABASE_URL=${_REACT_APP_FIREBASE_DATABASE_URL},REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID},REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET},REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID},REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID},REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}
      - --platform=managed

# build the service container image
  - name: "gcr.io/cloud-builders/docker"
    dir: "service"
    args:
      [
        "build",
        "--build-arg",
        "NODE_ENV=production",
        "-t",
        "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME_SERVICE}:$COMMIT_SHA",
        ".",
      ]

  # push the service container image to Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    dir: "service"
    args:
      ["push", "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME_SERVICE}:$COMMIT_SHA"]

  # Deploy the service container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - ${_SERVICE_NAME_SERVICE}
      - --image=${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME_SERVICE}:$COMMIT_SHA
      - --region=${_LOCATION}
      - --set-env-vars=MONGO_DB_URI=$$MONGO_DB_URI
      - --platform=managed
    secretEnv: ['MONGO_DB_URI']

images:
  - "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
  - "${_GCR_REGION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME_SERVICE}:$COMMIT_SHA"
# secretEnv:
#   [
#     "REACT_APP_FIREBASE_API_KEY",
#     "REACT_APP_FIREBASE_AUTH_DOMAIN",
#     "REACT_APP_FIREBASE_DATABASE_URL",
#     "REACT_APP_FIREBASE_PROJECT_ID",
#     "REACT_APP_FIREBASE_STORAGE_BUCKET",
#     "REACT_APP_FIREBASE_MESSAGING_SENDER_ID",
#     "REACT_APP_FIREBASE_APP_ID",
#     "REACT_APP_FIREBASE_MEASUREMENT_ID",
#   ]

substitutions:
  _LOCATION: asia-southeast1 # must be substituted
  _GCR_REGION: asia # must be substituted
  _SERVICE_NAME: peerprep # must be substituted
  _SERVICE_NAME_SERVICE: service
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGO_DB_URI/versions/latest
      env: 'MONGO_DB_URI'
# availableSecrets:
#   secretManager:
#     - versionName: projects/327190433280/secrets/firebase/versions/1
#       env: REACT_APP_FIREBASE_API_KEY

#         - REACT_APP_FIREBASE_AUTH_DOMAIN
#         - REACT_APP_FIREBASE_DATABASE_URL
#         - REACT_APP_FIREBASE_PROJECT_ID
#         - REACT_APP_FIREBASE_STORAGE_BUCKET
#         - REACT_APP_FIREBASE_MESSAGING_SENDER_ID
#         - REACT_APP_FIREBASE_APP_ID
#         - REACT_APP_FIREBASE_MEASUREMENT_ID
