steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "create-env"]
    env:
      - "REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}"
      - "REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}"
      - "REACT_APP_FIREBASE_DATABASE_URL=${_REACT_APP_FIREBASE_DATABASE_URL}"
      - "REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID}"
      - "REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}"
      - "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}"
      - "REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID}"
      - "REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}"
      - "COMMIT_SHA=${COMMIT_SHA}"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$_REACT_APP_FIREBASE_PROJECT_ID/github.com/garywongkai:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$_REACT_APP_FIREBASE_PROJECT_ID/github.com/garywongkai:$COMMIT_SHA",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - peerprep
      - --image=gcr.io/$PROJECT_ID//github.com/garywongkai:$COMMIT_SHA
      - --region=asia-southeast1
      - --platform=managed

images:
  - "gcr.io/$_REACT_APP_FIREBASE_PROJECT_ID/github.com/garywongkai:$COMMIT_SHA"

timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
