version: "3.9"

services:
  peerprep:
    build: ./peerprep
    ports:
      - "3000:3000"
    volumes:
      - ./peerprep:/app
      - /app/node_modules
    networks:
      - peerprep-network
    env_file:
      - .env

  question-service:
    build: ./question-service
    ports:
      - "5000:5000"
    volumes:
      - ./question-service:/app
      - /app/node_modules
    networks:
      - peerprep-network
    env_file:
      - .env

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - peerprep-network
    env_file:
      - .env
  
  matching-service:
    build: ./matching-service
    ports:
      - "5002:5002"
    volumes:
      - ./matching-service:/app
      - /app/node_modules
    networks:
      - peerprep-network
    env_file:
      - .env
  
  collaboration-service:
    build: ./collaboration-service
    ports:
      - "5003:5003"
    volumes:
      - ./collaboration-service:/app
      - /app/node_modules
    networks:
      - peerprep-network
    env_file:
      - .env

  code-execution-service:
    build: ./code-execution-service
    environment:
      - DOCKER_HOST=unix:///run/user/1000/docker.sock  # Use rootless Docker socket
    ports:
      - "5004:5004"
    volumes:
      - ./code-execution-service:/app
      - /app/node_modules
      - /run/user/1000/docker.sock:/run/user/1000/docker.sock  # Rootless Docker socket path
    networks:
      - peerprep-network
    env_file:
      - .env

networks:
  peerprep-network:
