# Use Node.js as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /service

# Copy package.json and yarn.lock to the container
COPY package*.json ./

# Install dependencies
# RUN yarn install --frozen-lockfile

# Install dependencies
RUN npm install

# Copy the app's source code to the container
COPY . .

# Build the React app

EXPOSE 5000

# Serve the build
CMD ["npm", "start"]
