version: "3.8"  # Specify the Docker Compose version

services:
  matching-service:
    build: .
    container_name: matching-service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_DB_URI=mongodb://mongo:27017/matching-db
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
